// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwg6bGbl2loOsOm5sz-UPZ8et_pWRcMU',
    appId: '1:215020299220:web:877659aaab15e3f1942c41',
    messagingSenderId: '215020299220',
    projectId: 'foundsoulsofficial-app',
    authDomain: 'foundsoulsofficial-app.firebaseapp.com',
    databaseURL: 'https://foundsoulsofficial-app-default-rtdb.firebaseio.com',
    storageBucket: 'foundsoulsofficial-app.firebasestorage.app',
    measurementId: 'G-D3BRWBFQX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQvTySPApMtcTM-Q4aaxf2MwjsznvxLw',
    appId: '1:215020299220:android:867c52bac594ec05942c41',
    messagingSenderId: '215020299220',
    projectId: 'foundsoulsofficial-app',
    databaseURL: 'https://foundsoulsofficial-app-default-rtdb.firebaseio.com',
    storageBucket: 'foundsoulsofficial-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLXL-eqG13Ab25C4fjg7V0QmT5VeeISkM',
    appId: '1:215020299220:ios:da106b7eb1252266942c41',
    messagingSenderId: '215020299220',
    projectId: 'foundsoulsofficial-app',
    databaseURL: 'https://foundsoulsofficial-app-default-rtdb.firebaseio.com',
    storageBucket: 'foundsoulsofficial-app.firebasestorage.app',
    androidClientId: '215020299220-3f7f51hjc8qjrdukpk9te8itju436u3c.apps.googleusercontent.com',
    iosClientId: '215020299220-nk5fksbog2jkr12d32p71hbeapuq7tqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foundSoulMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLXL-eqG13Ab25C4fjg7V0QmT5VeeISkM',
    appId: '1:215020299220:ios:da106b7eb1252266942c41',
    messagingSenderId: '215020299220',
    projectId: 'foundsoulsofficial-app',
    databaseURL: 'https://foundsoulsofficial-app-default-rtdb.firebaseio.com',
    storageBucket: 'foundsoulsofficial-app.firebasestorage.app',
    androidClientId: '215020299220-3f7f51hjc8qjrdukpk9te8itju436u3c.apps.googleusercontent.com',
    iosClientId: '215020299220-nk5fksbog2jkr12d32p71hbeapuq7tqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foundSoulMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXwg6bGbl2loOsOm5sz-UPZ8et_pWRcMU',
    appId: '1:215020299220:web:a39d407b534a804c942c41',
    messagingSenderId: '215020299220',
    projectId: 'foundsoulsofficial-app',
    authDomain: 'foundsoulsofficial-app.firebaseapp.com',
    databaseURL: 'https://foundsoulsofficial-app-default-rtdb.firebaseio.com',
    storageBucket: 'foundsoulsofficial-app.firebasestorage.app',
    measurementId: 'G-FGYJJ8X1LL',
  );

}